[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[deploy]
startCommand = "npx serve dist -s -l $PORT"
restartPolicyType = "on_failure"
